/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dev
 */
public class ManageBooks extends javax.swing.JFrame {

    String book_name, author;
    int book_id, quantity;
    DefaultTableModel model;
   
    
    /**
     * Creates new form ManageBooks
     */
    public ManageBooks() {
        initComponents();
        setBookDetails();
    }

    // to set the book details in the table
    public void setBookDetails(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");
            
            Statement st = con.createStatement();
            ResultSet rs =  st.executeQuery("Select * from book_details");
            
            while(rs.next()){
                String bookId = rs.getString("book_id");
                String bookName = rs.getString("book_name");
                String author = rs.getString("author");
                int quantity = rs.getInt("quantity");
                
                Object [] obj = {bookId,bookName,author,quantity};
                
                // using a model to set the values in the table
                model = (DefaultTableModel)tbl_bookDetails.getModel();
                // using the array to add data in the table
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
            
            
            
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBackManageBooks = new javax.swing.JLabel();
        lblBookIDLogo = new javax.swing.JLabel();
        lblBookID = new javax.swing.JLabel();
        txt_BookID = new app.bolivia.swing.JCTextField();
        lblBookNameLogo = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        txt_BookName = new app.bolivia.swing.JCTextField();
        lblAuthorNameLogo = new javax.swing.JLabel();
        lblAuthorName = new javax.swing.JLabel();
        txt_AuthorName = new app.bolivia.swing.JCTextField();
        lblQuantityLogo = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txt_Quantity = new app.bolivia.swing.JCTextField();
        btn_Login = new rojerusan.RSMaterialButtonCircle();
        btn_Login1 = new rojerusan.RSMaterialButtonCircle();
        btn_Login2 = new rojerusan.RSMaterialButtonCircle();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblCancelManageBooks = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bookDetails = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 60));

        lblBackManageBooks.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblBackManageBooks.setForeground(new java.awt.Color(255, 255, 255));
        lblBackManageBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        lblBackManageBooks.setText("Back");
        lblBackManageBooks.setPreferredSize(new java.awt.Dimension(100, 45));
        lblBackManageBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackManageBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBackManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBackManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        lblBookIDLogo.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblBookIDLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblBookIDLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(lblBookIDLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, 50));

        lblBookID.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblBookID.setForeground(new java.awt.Color(255, 255, 255));
        lblBookID.setText("Enter Book Id: ");
        jPanel1.add(lblBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        txt_BookID.setBackground(new java.awt.Color(102, 102, 255));
        txt_BookID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_BookID.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_BookID.setPlaceholder("Enter Book Id ...");
        txt_BookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_BookIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BookIDFocusLost(evt);
            }
        });
        txt_BookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BookIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 320, -1));

        lblBookNameLogo.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblBookNameLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblBookNameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(lblBookNameLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 50, 50));

        lblBookName.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(255, 255, 255));
        lblBookName.setText("Enter Book Name:");
        jPanel1.add(lblBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        txt_BookName.setBackground(new java.awt.Color(102, 102, 255));
        txt_BookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_BookName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_BookName.setPlaceholder("Enter Book Name ...");
        txt_BookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_BookNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BookNameFocusLost(evt);
            }
        });
        txt_BookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BookNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 320, -1));

        lblAuthorNameLogo.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblAuthorNameLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthorNameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(lblAuthorNameLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 50, 50));

        lblAuthorName.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblAuthorName.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthorName.setText("Enter Author Name:");
        jPanel1.add(lblAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        txt_AuthorName.setBackground(new java.awt.Color(102, 102, 255));
        txt_AuthorName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_AuthorName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_AuthorName.setPlaceholder("Enter Author Name ...");
        txt_AuthorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AuthorNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AuthorNameFocusLost(evt);
            }
        });
        txt_AuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AuthorNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_AuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 320, -1));

        lblQuantityLogo.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblQuantityLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(lblQuantityLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 50, 50));

        lblQuantity.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Enter Quantity: ");
        jPanel1.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        txt_Quantity.setBackground(new java.awt.Color(102, 102, 255));
        txt_Quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Quantity.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_Quantity.setPlaceholder("Enter Quantity ...");
        txt_Quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_QuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_QuantityFocusLost(evt);
            }
        });
        txt_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuantityActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 320, -1));

        btn_Login.setBackground(new java.awt.Color(255, 51, 51));
        btn_Login.setText("Delete");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 130, 60));

        btn_Login1.setBackground(new java.awt.Color(255, 51, 51));
        btn_Login1.setText("Add");
        btn_Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 130, 60));

        btn_Login2.setBackground(new java.awt.Color(255, 51, 51));
        btn_Login2.setText("Update");
        btn_Login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Login2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 60));

        lblCancelManageBooks.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        lblCancelManageBooks.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelManageBooks.setText("X");
        lblCancelManageBooks.setPreferredSize(new java.awt.Dimension(100, 45));
        lblCancelManageBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelManageBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCancelManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblCancelManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 80, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText("  Manage Books");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 280, -1));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 380, 5));

        tbl_bookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID ", "Book Name", "Author", "Quantity"
            }
        ));
        tbl_bookDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_bookDetails.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_bookDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookDetails.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_bookDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        tbl_bookDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_bookDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        tbl_bookDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_bookDetails.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_bookDetails.setRowHeight(40);
        tbl_bookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bookDetails);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 970, 370));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 1140, 830));

        setSize(new java.awt.Dimension(1724, 824));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackManageBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackManageBooksMouseClicked
       HomePage home = new HomePage();
       home.setVisible(true);
       // this will dispose of the current frame and open the homepage frame
       dispose();
    }//GEN-LAST:event_lblBackManageBooksMouseClicked

    private void txt_BookIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BookIDFocusGained

    private void txt_BookIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookIDFocusLost
        // to check whether username is already in use
        
    }//GEN-LAST:event_txt_BookIDFocusLost

    private void txt_BookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BookIDActionPerformed

    private void txt_BookNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BookNameFocusGained

    private void txt_BookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookNameFocusLost
        // to check whether username is already in use
       
    }//GEN-LAST:event_txt_BookNameFocusLost

    private void txt_BookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BookNameActionPerformed

    private void txt_AuthorNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AuthorNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AuthorNameFocusGained

    private void txt_AuthorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AuthorNameFocusLost
        // to check whether username is already in use
      
    }//GEN-LAST:event_txt_AuthorNameFocusLost

    private void txt_AuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AuthorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AuthorNameActionPerformed

    private void txt_QuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QuantityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuantityFocusGained

    private void txt_QuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QuantityFocusLost
        // to check whether username is already in use
        
    }//GEN-LAST:event_txt_QuantityFocusLost

    private void txt_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuantityActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_Login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Login2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Login2ActionPerformed

    private void btn_Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Login1ActionPerformed

    private void lblCancelManageBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelManageBooksMouseClicked
        System.exit(0);    
    }//GEN-LAST:event_lblCancelManageBooksMouseClicked

    private void tbl_bookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseClicked
        
        int rowNo = tbl_bookDetails.getSelectedRow();
        
        TableModel model = tbl_bookDetails.getModel();
        
        //using the values from the model and setting it in the textfields
        txt_BookID.setText(model.getValueAt(rowNo, 0).toString());
        txt_BookName.setText(model.getValueAt(rowNo, 1).toString());
        txt_AuthorName.setText(model.getValueAt(rowNo, 2).toString());
        txt_Quantity.setText(model.getValueAt(rowNo, 3).toString());
        
    }//GEN-LAST:event_tbl_bookDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_Login;
    private rojerusan.RSMaterialButtonCircle btn_Login1;
    private rojerusan.RSMaterialButtonCircle btn_Login2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthorName;
    private javax.swing.JLabel lblAuthorNameLogo;
    private javax.swing.JLabel lblBackManageBooks;
    private javax.swing.JLabel lblBookID;
    private javax.swing.JLabel lblBookIDLogo;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblBookNameLogo;
    private javax.swing.JLabel lblCancelManageBooks;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantityLogo;
    private rojeru_san.complementos.RSTableMetro tbl_bookDetails;
    private app.bolivia.swing.JCTextField txt_AuthorName;
    private app.bolivia.swing.JCTextField txt_BookID;
    private app.bolivia.swing.JCTextField txt_BookName;
    private app.bolivia.swing.JCTextField txt_Quantity;
    // End of variables declaration//GEN-END:variables
}
